trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  inputs:
    mavenPomFile: 'Javateam/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'

- task: Bash@3
  name: FindJar
  displayName: 'Find built JAR file'
  inputs:
    targetType: 'inline'
    script: |
      echo "##[group]Locating built JAR file..."
      jar_file=$(find Javateam/target -type f -name "*.jar" | grep -v 'original' | head -n 1)
      if [[ -z "$jar_file" ]]; then
        echo "##[error]No JAR file found!"
        exit 1
      fi
      echo "Found JAR: $jar_file"
      echo "##vso[task.setvariable variable=jarPath]$jar_file"
      echo "##[endgroup]"

- task: Bash@3
  displayName: 'Run Java App'
  inputs:
    targetType: 'inline'
    script: |
      echo "Running app from: $(jarPath)"
      java -cp "$(jarPath)" com.dineshonjava.App
